noarch_platforms:
- linux_64
- osx_64
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
bot:
    # only automerge on successful version PRs, migrations are not automerged
    automerge: 'version'
    # only open PRs if resulting environment is solvable, useful for tightly coupled packages
    check_solvable: true
    inspection: update-all
